TPs/CBTSWE2_TP02/Models/Entity/BillOfLading.cs
namespace TP02.Models.Entity;

public class BillOfLading
{
    public int Id { get; set; }
    public string Numero { get; set; }
    public string Consignee { get; set; }
    public string Navio { get; set; }

    public virtual ICollection<Container>? Containers { get; set; }
}

TPs/CBTSWE2_TP02/Controllers/BillOfLadingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TP02.Context;
using TP02.Models.Entity;

namespace TP02.Controllers
{
    public class BillOfLadingsController : Controller
    {
        private readonly TpContext _context;

        public BillOfLadingsController(TpContext context)
        {
            _context = context;
        }

        // GET: BillOfLadings
        public async Task<IActionResult> Index()
        {
              return _context.BillOfLadings != null ? 
                          View(await _context.BillOfLadings.ToListAsync()) :
                          Problem("Entity set 'TpContext.BillOfLadings'  is null.");
        }

        // GET: BillOfLadings/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.BillOfLadings == null)
            {
                return NotFound();
            }

            var billOfLading = await _context.BillOfLadings
                .Include(b => b.Containers)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (billOfLading == null)
            {
                return NotFound();
            }

            return View(billOfLading);
        }

        // GET: BillOfLadings/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: BillOfLadings/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Numero,Consignee,Navio")] BillOfLading billOfLading)
        {
            if (ModelState.IsValid)
            {
                _context.Add(billOfLading);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(billOfLading);
        }

        // GET: BillOfLadings/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.BillOfLadings == null)
            {
                return NotFound();
            }

            var billOfLading = await _context.BillOfLadings.FindAsync(id);
            if (billOfLading == null)
            {
                return NotFound();
            }
            return View(billOfLading);
        }

        // POST: BillOfLadings/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Numero,Consignee,Navio")] BillOfLading billOfLading)
        {
            if (id != billOfLading.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(billOfLading);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BillOfLadingExists(billOfLading.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(billOfLading);
        }

        // GET: BillOfLadings/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.BillOfLadings == null)
            {
                return NotFound();
            }

            var billOfLading = await _context.BillOfLadings
                .FirstOrDefaultAsync(m => m.Id == id);
            if (billOfLading == null)
            {
                return NotFound();
            }

            return View(billOfLading);
        }

        // POST: BillOfLadings/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.BillOfLadings == null)
            {
                return Problem("Entity set 'TpContext.BillOfLadings'  is null.");
            }
            var billOfLading = await _context.BillOfLadings.FindAsync(id);
            if (billOfLading != null)
            {
                _context.BillOfLadings.Remove(billOfLading);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool BillOfLadingExists(int id)
        {
          return (_context.BillOfLadings?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

TPs/CBTSWE2_TP02/Controllers/ContainersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using TP02.Context;
using TP02.Models.Entity;

namespace TP02.Controllers
{
    public class ContainersController : Controller
    {
        private readonly TpContext _context;

        public ContainersController(TpContext context)
        {
            _context = context;
        }

        // GET: Containers
        public async Task<IActionResult> Index()
        {
            var tpContext = _context.Containers.Include(c => c.Bill);
            return View(await tpContext.ToListAsync());
        }

        // GET: Containers/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Containers == null)
            {
                return NotFound();
            }

            var container = await _context.Containers
                .Include(c => c.Bill)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (container == null)
            {
                return NotFound();
            }

            return View(container);
        }

        // GET: Containers/Create
        public IActionResult Create()
        {
            ViewData["Bills"] = new SelectList(_context.BillOfLadings, "Id", "Numero");
            return View();
        }

        // POST: Containers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Numero,Tipo,Tamanho,BillId")] Container container)
        {
            if (ModelState.IsValid)
            {
                _context.Add(container);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["Bills"] = new SelectList(_context.BillOfLadings, "Id", "Id", container.BillId);
            return View(container);
        }

        // GET: Containers/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Containers == null)
            {
                return NotFound();
            }

            var container = await _context.Containers.FindAsync(id);
            if (container == null)
            {
                return NotFound();
            }
            ViewData["Bills"] = new SelectList(_context.BillOfLadings, "Id", "Numero", container.BillId);
            return View(container);
        }

        // POST: Containers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Numero,Tipo,Tamanho,BillId")] Container container)
        {
            if (id != container.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(container);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ContainerExists(container.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["Bills"] = new SelectList(_context.BillOfLadings, "Id", "Id", container.BillId);
            return View(container);
        }

        // GET: Containers/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Containers == null)
            {
                return NotFound();
            }

            var container = await _context.Containers
                .Include(c => c.Bill)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (container == null)
            {
                return NotFound();
            }

            return View(container);
        }

        // POST: Containers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Containers == null)
            {
                return Problem("Entity set 'TpContext.Containers'  is null.");
            }
            var container = await _context.Containers.FindAsync(id);
            if (container != null)
            {
                _context.Containers.Remove(container);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ContainerExists(int id)
        {
          return (_context.Containers?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

TPs/CBTSWE2_TP02/Views/BillOfLadings/Create.cshtml
@using TP02.Models.Entity;
@model BillOfLading

@{
    ViewData["Title"] = "Cadastrar - BL";
}

<h1 class="text-center mb-4">Cadastrar Nova BL</h1>

<h4 id="text-center">Informações da BL</h4>
<hr />

<div class="row justify-content-center">
    <div class="col-md-6">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="alert alert-danger"></div>

            <div class="mb-3">
                <label asp-for="Numero" class="form-label"></label>
                <input asp-for="Numero" class="form-control" placeholder="Número da BL" />
                <span asp-validation-for="Numero" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Consignee" class="form-label"></label>
                <input asp-for="Consignee" class="form-control" placeholder="Consignee" />
                <span asp-validation-for="Consignee" class="text-danger"></span>
            </div>

            <div class="mb-3">
                <label asp-for="Navio" class="form-label"></label>
                <input asp-for="Navio" class="form-control" placeholder="Navio" />
                <span asp-validation-for="Navio" class="text-danger"></span>
            </div>

            <div class="d-grid gap-2">
                <button type="submit" class="btn btn-primary">Cadastrar</button>
            </div>
        </form>
    </div>
</div>

<div class="mt-4 text-center">
    <a asp-action="Index" class="btn btn-secondary">Voltar para lista</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

TPs/CBTSWE2_TP02/Views/BillOfLadings/Delete.cshtml
@using TP02.Models.Entity;
@model BillOfLading

@{
    ViewData["Title"] = "Deletar - Bill";
}

<h1>Deletar</h1>

<h3>Tem certeza de que deseja excluir isso?</h3>
<div>
    <h4>BL</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Numero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Numero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Consignee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Consignee)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Navio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Navio)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Apagar" class="btn btn-danger" />
        <a asp-action="Index" class="btn btn-secondary">Voltar para lista</a>
    </form>
</div>

TPs/CBTSWE2_TP02/Views/BillOfLadings/Details.cshtml
@using TP02.Models.Entity;
@model BillOfLading

@{
    ViewData["Title"] = "Detalhes - Bill";
}

<h1>Detalhes</h1>

<div>
    <h4>BL</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Numero)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Numero)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Consignee)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Consignee)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Navio)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Navio)
        </dd>
    </dl>

    <div>
        <h4>Containers</h4>

        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayName("Numero")
                    </th>
                    <th>
                        @Html.DisplayName("Tipo")
                    </th>
                    <th>
                        @Html.DisplayName("Tamanho")
                    </th>
                    <th>
                        @Html.DisplayName("Bill")
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Containers)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Numero)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Tipo)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Tamanho)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Bill.Id)
                        </td>
                        <td>
                            <a asp-action="Edit" asp-controller="Containers" asp-route-id="@item.Id">Editar</a> |
                            <a asp-action="Details" asp-controller="Containers"  asp-route-id="@item.Id">Detalhes</a> |
                            <a asp-action="Delete" asp-controller="Containers"  asp-route-id="@item.Id">Deletar</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.Id" class="btn btn-primary">Editar</a>
    <a asp-action="Index" class="btn btn-secondary">Voltar para lista</a>
</div>

TPs/CBTSWE2_TP02/Views/BillOfLadings/Edit.cshtml
@using TP02.Models.Entity;
@model BillOfLading

@{
    ViewData["Title"] = "Editar - BL";
}

<h1>Editar</h1>

<h4>BL - @Model.Numero</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Numero" class="control-label"></label>
                <input asp-for="Numero" class="form-control" />
                <span asp-validation-for="Numero" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Consignee" class="control-label"></label>
                <input asp-for="Consignee" class="form-control" />
                <span asp-validation-for="Consignee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Navio" class="control-label"></label>
                <input asp-for="Navio" class="form-control" />
                <span asp-validation-for="Navio" class="text-danger"></span>
            </div>
            <br />
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<br />
<div>
    <a asp-action="Index" class="btn btn-secondary">Voltar para lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

TPs/CBTSWE2_TP02/Views/BillOfLadings/Index.cshtml
@using TP02.Models.Entity;
@model IEnumerable<BillOfLading>

@{
    ViewData["Title"] = "BLs";
}

<div class="d-flex justify-content-between align-items-center mb-3">
    <h1 class="mb-0">Tabela de BLs</h1>
    <a asp-action="Create" class="btn btn-secondary">Novo BL</a>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Numero)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Consignee)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Navio)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Numero)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Consignee)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Navio)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Editar</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Detalhes</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Deletar</a>
                </td>
            </tr>
        }
    </tbody>
</table>